sbr:
  service:
    mongodb: # MongoDB configuration
      config:
        #        Indexed(expireAfter = "10s") String expireAfterTenSeconds;
        #        Indexed(expireAfter = "1d") String expireAfterOneDay;
        #        Indexed(expireAfter = "P2D") String expireAfterTwoDays;
        retention-time: 10s
        primary:
          host: localhost
          port: 27017
          database: primary-profiles-collections
          authentication-database: admin
          username: admin
          password: changeit
          repositories:
            enable: true